import { UserRole } from './index';

export const PERMISSIONS = {
  // 仪表板权限
  DASHBOARD_READ: 'dashboard:read',
  
  // 会员卡管理权限
  CARDS_READ: 'cards:read',
  CARDS_MANAGE: 'cards:manage',
  CARDS_IMPORT: 'cards:import',
  CARDS_DEVICES_READ: 'cards:devices:read',
  CARDS_DEVICES_MANAGE: 'cards:devices:manage',
  
  // 权益回收池权限
  RECOVERY_READ: 'recovery:read',
  RECOVERY_APPROVE: 'recovery:approve',
  RECOVERY_EXCHANGE: 'recovery:exchange',
  
  // 分账管理权限
  SHARING_READ: 'sharing:read',
  SHARING_RULES_MANAGE: 'sharing:rules:manage',
  SHARING_DETAILS_READ: 'sharing:details:read',
  
  // 订单管理权限
  ORDERS_READ: 'orders:read',
  ORDERS_MANAGE: 'orders:manage',
  
  // 合作伙伴权限
  PARTNERS_READ: 'partners:read',
  PARTNERS_MANAGE: 'partners:manage',
  
  // 报表权限
  REPORTS_READ: 'reports:read',
  REPORTS_EXPORT: 'reports:export',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS = {
  [UserRole.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CARDS_READ,
    PERMISSIONS.CARDS_MANAGE,
    PERMISSIONS.CARDS_IMPORT,
    PERMISSIONS.CARDS_DEVICES_READ,
    PERMISSIONS.CARDS_DEVICES_MANAGE,
    PERMISSIONS.RECOVERY_READ,
    PERMISSIONS.RECOVERY_APPROVE,
    PERMISSIONS.RECOVERY_EXCHANGE,
    PERMISSIONS.SHARING_READ,
    PERMISSIONS.SHARING_RULES_MANAGE,
    PERMISSIONS.SHARING_DETAILS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.PARTNERS_READ,
    PERMISSIONS.PARTNERS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [UserRole.PARTNER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CARDS_READ,
    PERMISSIONS.CARDS_DEVICES_READ,
    PERMISSIONS.RECOVERY_READ,
    PERMISSIONS.SHARING_READ,
    PERMISSIONS.SHARING_DETAILS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.REPORTS_READ,
  ],
  [UserRole.OPERATOR]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CARDS_READ,
    PERMISSIONS.CARDS_MANAGE,
    PERMISSIONS.CARDS_DEVICES_READ,
    PERMISSIONS.CARDS_DEVICES_MANAGE,
    PERMISSIONS.RECOVERY_READ,
    PERMISSIONS.RECOVERY_APPROVE,
    PERMISSIONS.SHARING_READ,
    PERMISSIONS.SHARING_DETAILS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.PARTNERS_READ,
    PERMISSIONS.REPORTS_READ,
  ],
} as const;
